import '@/styles/globals.css';
import Head from 'next/head';

// import localFont from '@next/font/local';

// const BNazanin = localFont({
//   src: '../assets/font/MjBeirut.ttf',
//   variable: '--font-MjBeirut',
// });

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>فروشگاه فربد</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}
