import '@/styles/globals.css';
import Head from 'next/head';

import { Provider } from 'react-redux';
import store from '@/src/app/store';

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>فروشگاه فربد</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <Component {...pageProps} />
      </Provider>
    </>
  );
}

// import localFont from '@next/font/local';

// const BNazanin = localFont({
//   src: '../assets/font/MjBeirut.ttf',
//   variable: '--font-MjBeirut',
// });
